import hudson.plugins.git.GitSCM // So that we can make scmPlus
import hudson.plugins.git.UserRemoteConfig // So that we can add master to the scm

node('TEST-gb-cmb-dt-022')
{
    def git_commit_text
    def changed_files
    def archive_url_root = env.U_ARCHIVE_URL
    def summary_file = "summary.txt"
    def test_report_file = "test_report.xml"
    def debug_file = "debug.txt"
    def console_output_file_path = "controller_output.txt"
    def controller_name = env.NODE_NAME.reverse().take(3).reverse() // Last three characters of node name
    def repo_url = "repo_url_unknown"
    def hash_to_test = "hash_to_test_unknown"
    def hash_master = "hash_master_unknown"
    def archive_url = "archive_url_not_set"
    def archive_credentials = env.U_ARCHIVE_CREDENTIALS
    def remote_control_port = 50124
    def return_value = 1

    // All the stages go here
    timeout(time: 60, unit: 'MINUTES') {
        stage("Info") {
            //environment = bat(script: "@echo off & set", returnStdout: true).trim()
            //println "Environment variables are: \n" + environment

            // For debug purposes, print out the entries in the scm map
            // passed to us from the CloudBees magic
            println "scm contains: " + scm.properties.each{entry -> "$entry.key = $entry.value"} + "\n"
        }

        stage("Environment Check") {
            if (bat(script: "@echo off & python --version", returnStatus: true) != 0) {
                error("Python is not available on this node.")
            }
            if (!archive_url_root) {
                error("env.U_ARCHIVE_URL is not set.")
            }
            if (!archive_credentials) {
                error("env.U_ARCHIVE_CREDENTIALS is not set.")
            }
        }

        stage("Fetch") {
            // Create a modified version of the remote configs in scm to
            // add master.  With master fetched as well as the
            // branch-under-test  we can get the file difference between the two
            println "Creating scmPlus to add fetch of master...\n"
            refspec = scm.userRemoteConfigs[0].refspec
            if (!scm.userRemoteConfigs[0].refspec.contains("/master:")) {
                refspec += " refs/heads/master:refs/remotes/origin/master"
            }
            userRemoteConfigPlus = new UserRemoteConfig(scm.userRemoteConfigs[0].url,
                                                        scm.userRemoteConfigs[0].name,
                                                        refspec,
                                                        scm.userRemoteConfigs[0].credentialsId)

            scmPlus = new GitSCM([userRemoteConfigPlus],
                                 scm.branches,
                                 scm.doGenerateSubmoduleConfigurations,
                                 scm.submoduleCfg,
                                 scm.browser,
                                 scm.gitTool,
                                 scm.extensions)

            // For debug purposes, print out scmPlus
            println "scmPlus contains: " + scmPlus.properties.each{entry -> "$entry.key = $entry.value"} + "\n"

            // Get the code
            println "checkout() branch \"" + scmPlus.branches[0] + "\" and also fetch master...\n"
            scmMap = checkout scmPlus

            // Note: no need to recurse submodules since we don't use submodules in the automation part of the repo

            // For debug purposes, print out the entries in the scm
            // map returned by checkout
            println "checkout() returned: " + scmMap.each{entry -> "$entry.key = $entry.value"}

            // Populate the repo URL, removing ".git" from the end as it is superfluous
            repo_url = scm.userRemoteConfigs[0].url.replaceAll("\\.git", "")
            println "URL of repo we are testing is: " + repo_url + "."

            // Populate the hash of the commit we are to test
            hash_to_test = scmMap["GIT_COMMIT"]
            println "Hash of the commit we are testing is: " + hash_to_test + "."

            // Get the hash of master, removing the line-feed off the end
            hash_master = bat(script: "@echo off & git rev-parse remotes/origin/master", returnStdout: true)
            hash_master = hash_master.replaceAll("\\n", "")
            println "Hash of master is: " + hash_master + "."

            // Populate the place to archive the files to
            def time_now = new Date()
            archive_url = archive_url_root + "/" + time_now.format("yyyyMMddHHmmss") + "_" + hash_to_test
            println "Archive URL will be: " + archive_url + "."

            // Use git to get the last commit message, @echo off to avoid capturing the command
            // output as well as the returned text
            git_commit_text = bat(script: "@echo off & git log -1 --pretty=%%B", returnStdout: true)

            if (git_commit_text) {
                // Convert newlines to "/n" and quotation marks to back-ticks to prevent them
                // screwing up the command-line they get passed to lower down
                git_commit_text = git_commit_text.replaceAll("\\n", "\\\\n").replaceAll("\"", "`")
                println "Last commit message was: \"" + git_commit_text + "\""
            } else {
                println "Unable to get last commit message."
            }
        }

        if ((env.CHANGE_TARGET && env.CHANGE_ID) || !env.JOB_BASE_NAME || (env.JOB_BASE_NAME == "master")) {
            println "Either this is a pull request or we're on master or the branch name is not specified: all tests will be run."
        } else {
            // This is not master and not yet a pull request,
            // so we can save time by only running selected tests 
            println "This is not master, checking which tests to run..."
            try {
                stage("Check Branch Differences") {
                    if (env.JOB_BASE_NAME) {
                        // No user direction so use git to get the list
                        // of file differences from main, @echo off to avoid
                        // capturing the command output as well as the  returned text
                        println "Checking for changed files between master and " + env.JOB_BASE_NAME + "..."
                        changed_files = bat(script: "@echo off & git diff --name-only origin/master", returnStdout: true).trim()
                        changed_files = changed_files.replaceAll("\n", " ");
                        println "Changed file(s) were: " + changed_files
                    } else {
                        println "Environment variable JOB_BASE_NAME not found, unable to determine the files that are different to master."
                    }
                }
            } catch (e) {
                println "Git was unable to determine the files that are different to master."
            }
        }

        // Add a link to where the results will be in the Jenkins GUI
        currentBuild.description = "Agents <a href='${archive_url}'>results files</a> (link works after first agent finishes)";

        // Using the try/catch pattern as recommended in this post:
        // https://stackoverflow.com/questions/48989238/post-equivalent-in-scripted-pipeline
        // ... in order to make sure that currentBuild.description
        // is always updated while in the "scripted pipeline" world
        dir ("port\\platform\\common\\automation") {
            try {
                // Call python to run the necessary builds and tests
                if (changed_files) {
                    stage("Test Selected") {
                        return_value = bat(script: "python u_process_wrapper.py -r ${remote_control_port} -k 60 u_controller_client.py -r ${remote_control_port} -s ${summary_file} -t ${test_report_file} -d ${debug_file} -o ${console_output_file_path} -a ${archive_url} -c ${archive_credentials} ${controller_name} ${repo_url} #${hash_master} #${hash_to_test} \"${git_commit_text}\" ${changed_files}", returnStatus: true)
                        if (return_value != 0) {
                            error("Running selected ubxlib test(s) returned error " + return_value + ".")
                        } else {
                            println "The selected ubxlib test(s) passed."
                        }
                    }
                } else {
                    stage("Test All") {
                        // Call python to run all tests
                        return_value = bat(script: "python u_process_wrapper.py -r ${remote_control_port} -k 60 u_controller_client.py -r ${remote_control_port} -s ${summary_file} -t ${test_report_file} -d ${debug_file} -o ${console_output_file_path} -a ${archive_url} -c ${archive_credentials} ${controller_name} ${repo_url} #${hash_master} #${hash_to_test} \"test: *\"", returnStatus: true)
                        if (return_value != 0) {
                            error("Running all ubxlib tests returned " + return_value + " failed test(s).")
                        } else {
                            println "All ubxlib tests passed."
                        }
                    }
                }
            } catch (e) {
                println "Failed."
                // Since we're catching the exception in order to report on it,
                // we need to re-throw it, to ensure that the build is marked as failed
                throw e
            } finally {
                // Update the link in the Jenkins GUI to include one for the summary file
                currentBuild.description = "Agents <a href='${archive_url + "/" + summary_file}'>summary</a> and <a href='${archive_url}'>final results files</a>";
                stage("Termination") {
                    // Wait for the processes to end
                    while (bat(script: "python u_process_checker_is_running.py -t 300", returnStatus: true) == 0) {
                        println "Processes still running..."
                    }
                }
            }
        }

    }
}
