---
name: style

on:
  pull_request:
  push:

jobs:
  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dependencies
        run: |
          sudo apt update
          sudo apt install doxygen cmake python3
          # Install AStyle the hard way in order to get 3.4.10
          wget https://sourceforge.net/projects/astyle/files/astyle/astyle%203.4/astyle-3.4.10.tar.bz2/download -O astyle.tar.bz2
          tar -xf astyle.tar.bz2
          cd astyle-3.4.10
          mkdir as-gcc-exe
          cd as-gcc-exe
          cmake ../
          make
          make install
      - name: check
        run: |
          python3 astyle.py && UBX_WORKDIR="$(pwd)" doxygen
